export const types = {
    // Sync
    FILL_TASKS:  'FILL_TASKS',
    CREATE_TASK: 'CREATE_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    COMPLETE_TASK: 'COMPLETE_TASK',
    INCOMPLETE_TASK: 'INCOMPLETE_TASK',
    FAVORITE_TASK: 'FAVORITE_TASK',
    UNFAVORITE_TASK: 'UNFAVORITE_TASK',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE',

    // Async
    FETCH_TASKS_ASYNC: 'FETCH_TASKS_ASYNC',
    CREATE_TASK_ASYNC: 'CREATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC: 'REMOVE_TASK_ASYNC',
    COMPLETE_TASK_ASYNC: 'COMPLETE_TASK_ASYNC',
    INCOMPLETE_TASK_ASYNC: 'INCOMPLETE_TASK_ASYNC',
    FAVORITE_TASK_ASYNC: 'FAVORITE_TASK_ASYNC',
    UNFAVORITE_TASK_ASYNC: 'UNFAVORITE_TASK_ASYNC',
    UPDATE_MESSAGE_ASYNC: 'UPDATE_MESSAGE_ASYNC',
};
